### ISSUE TITLE
Tracking docs

### ISSUE THREAD

**Issue by h-a-n-a** [web-infra-dev/rspack-website#2]
# Home page

# RoadMap

# Guide

- [ ] Guide @hardfist 
  - [x] Installation guide
  - [x] First Bundle
  - [x] Use config file
  - [x] Npm scripts
  - [x] Create from template
  - [ ] Create from modernjs 
- [x] #4 @h-a-n-a 
    - [x] Builtin support
      - [x] JavaScript/JSX
      - [x] TypeScript/JSX
      - [x] JSON 
      - [x] Asset Module
      - [x] CSS Support
     - [ ] Extend via Plugin, loader
       - [x] Less
       - [x] Sass
       - [ ] HTML
       - [x] #14
       - [x] #35
 - [x] #5 @h-a-n-a 
   - [x] React
   - [x] SolidJS
 - [x] devServer  @ahabhgk 
   - [x]  HMR
   - [x] Proxy
 - [x] Optimization
   - [x] Code Splitting, Bundle Splitting @hyf0 
   - [x] Tree Shaking @IWANABETHATGUY 
   - [x] JS Optimization @jerrykingxyz 
   - [x] Bundle Analysis @hardfist 
 - [x] #10
   - [ ] Loader API(link)
   - [ ] Tutorial
   - [ ] Bulitin loader
   - [ ] Loader compat(link)
 - [x] #11
   - [ ] Plugin API(link)
   - [ ] Tutorial
   - [ ] Plugin compat(link)
 - [ ] Deploy @hardfist 
  

# Configuration

- [X] entry
- [X] mode
- [X] target
- [x] context
- [X] output
- [X] resolve https://github.com/modern-js-dev/rspack-website/pull/20
- [X] module
- [ ] builtins (mark as unstable)
  - [x] #18
  - [x] css,postcss @IWANABETHATGUY 
  - [x] #19
  - [x] #32
  - [x] no_emit_assets, progress @h-a-n-a 
- [x] #17
- [x] #12
- [x] #16
- [x] #39
- [x] devServer @ahabhgk 
- [x] #13
- [x] #26
- [x] experiments 
- [x] #45

# API

- [x] Node API @ahabhgk (on-hold)
- [ ] Runtime API @underfin 
- [x] #69
- [ ] Plugin API @hardfist 
- [ ] DevServer API @hardfist 
- [x] #50

# CLI @hardfist 

- [x] CLI commands 

# Glossary 

# Architecture @hyf0 @h-a-n-a 

# Migrating

- [x] Migrate from webpack
- [ ] Modern-js integration(link) @9aoy 
- [ ] Compat-page @ahabhgk 
  - [ ] Loader 
  - [ ] Plugin

# Benchmark @IWANABETHATGUY @ahabhgk @chenjiahan 
- [x] Dev
- [x] Build
- [x] HMR

# Blog @hardfist 
- [ ] Release notes
- [ ] Technical notes

# Showcase(Example) @chenjiahan 
- [ ] Arco

**Comment by h-a-n-a** [comment]
Closed as completed
