### ISSUE TITLE
[Tracking issue] improve migration guide

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack-website#257]
the migration guide is too simple to guide real world application migration, there're following things we can do to simplify the migration process 
```[tasklist]
### My tasks
- [ ] https://github.com/web-infra-dev/rspack-website/issues/258
- [ ] https://github.com/web-infra-dev/rspack-website/issues/259
- [ ] https://github.com/web-infra-dev/rspack-website/issues/260
```
